services:
  mysql:
    image: mysql:latest
    container_name: mysql-con
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: MDBS
      MYSQL_USER: MDBS
      MYSQL_PASSWORD: 0897
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe 
    container_name: oracle-con
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: YourPassword123
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always

volumes:
  mysql_data:
  oracle_data:
