CREATE TABLE holds (
  hold_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id      BIGINT NOT NULL REFERENCES accounts(account_id),
  amount          NUMERIC(19,4) NOT NULL,
  status          VARCHAR(1) NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
