CREATE TABLE ledger_entries (
  entry_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_id      BIGINT NOT NULL REFERENCES transactions(txn_id),
  account_id  BIGINT NOT NULL REFERENCES accounts(account_id),
  amount      NUMERIC(19,4) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);