CREATE TABLE transactions (
  txn_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            VARCHAR(1) NOT NULL,
  status          VARCHAR(1) NOT NULL,
  src_account_id  BIGINT,
  dst_account_id  BIGINT,
  src_bank        VARCHAR(2),
  dst_bank        VARCHAR(2),
  amount          NUMERIC(19,4) NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);