CREATE TABLE holds (
  hold_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id      NUMBER(19) NOT NULL,
  amount          NUMBER(19,4) NOT NULL,
  status          VARCHAR2(1) DEFAULT 'O' NOT NULL,   
  idempotency_key VARCHAR2(100) NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_hold_account FOREIGN KEY (account_id) REFERENCES accounts(account_id),
  CONSTRAINT ux_hold_idemp UNIQUE (idempotency_key)
);