CREATE TABLE ledger_entries (
  entry_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_id      NUMBER(19) NOT NULL,
  account_id  NUMBER(19) NOT NULL,
  amount      NUMBER(19,4) NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_ledger_txn     FOREIGN KEY (txn_id)    REFERENCES transactions(txn_id),
  CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);