CREATE TABLE transactions (
  txn_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            VARCHAR2(1) NOT NULL,
  status          VARCHAR2(1) NOT NULL,           
  src_account_id  NUMBER(19),
  dst_account_id  NUMBER(19),
  dst_bank        VARCHAR2(2),
  amount          NUMBER(19,4) NOT NULL,
  idempotency_key VARCHAR2(100) NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_txn_src FOREIGN KEY (src_account_id) REFERENCES accounts(account_id),
  CONSTRAINT ux_txn_idemp UNIQUE (idempotency_key)
);