services:
  api:
    build:
      context: ..
      dockerfile: Docker/dockerfile   
      target: dev
    env_file: ../BE/.env.dev
    command: flask --app BE/app.py run --host=0.0.0.0 --port=8000 --debug
    depends_on: []
    ports:
      - "5000:5000"
    volumes:
      - ..:/app:cached