#도커 파일 포맷 버젼
version: "3.9"

#올릴려는 서비스들 명시
services:
  # -------------------
  # MongoDB 설정
  # -------------------
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

  # -------------------
  # MySQL 설정
  # -------------------
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  # -------------------
  # Oracle Database (XE)  설정
  # -------------------
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    restart: always
    ports:
      - "1521:1521"   # listener
      - "5500:5500"   # EM Express
    environment:
      ORACLE_PASSWORD: rootpass
      APP_USER: testuser
      APP_USER_PASSWORD: testpass
    volumes:
      - oracle_data:/opt/oracle/oradata

  # -------------------
  # PostgreSQL 설정
  # -------------------
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

# -------------------
# Volumes - 데이터 영구 보존
# -------------------
volumes:
  mongo_data:
  mysql_data:
  oracle_data:
  postgres_data: