services:
  api:
    build:
      context: ..
      dockerfile: Docker/dockerfile
      target: dev
    env_file: ../BE/.env.dev          # 여기에 기본값들 (.env.dev)
    environment:                      # ← 여기 추가
      APP_PROFILE: dev
      PYTHON_ORACLEDB_THIN: "1"       # oracledb 얇은 모드 강제
      TNS_ADMIN: ""                   # TNS 경로 무력화(빈 문자열)
      ORACLE_HOME: ""                 # Thick 모드 유도 방지
    command: flask --app BE/app.py run --host=0.0.0.0 --port=5000 --debug
    depends_on: []
    ports:
      - "5000:5000"
    volumes:
      - ..:/app:cached

  web:
    build:
      context: ..
      dockerfile: Docker/fe.dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:5000"
      WATCHPACK_POLLING: "true"   # 도커 파일감지 안정화(Next)
    ports:
      - "5173:5173"
    volumes:
      - ../FE:/app
      - /app/node_modules
    depends_on:
      - api
