-- Oracle 데이터 초기화 및 IDENTITY 시퀀스 리셋 (DROP/CREATE 버전)
-- MySQL과 동일한 방식: 테이블 재생성으로 IDENTITY 완전 리셋
-- PL/SQL 익명 블록으로 여러 DDL/DML을 하나의 실행 단위로 처리

BEGIN
  -- 1. 트랜잭션 데이터 삭제 및 IDENTITY 리셋 (DROP/CREATE)
  -- FK 제약 때문에 자식 테이블부터 DROP
  EXECUTE IMMEDIATE 'DROP TABLE ledger_entries CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE holds CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE transactions CASCADE CONSTRAINTS';

  -- 테이블 재생성 (IDENTITY START WITH 1로 초기화)
  EXECUTE IMMEDIATE '
    CREATE TABLE transactions (
      txn_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
      type            VARCHAR2(1) NOT NULL,
      status          VARCHAR2(1) NOT NULL,
      src_account_id  NUMBER(19),
      dst_account_id  NUMBER(19),
      src_bank        VARCHAR2(2),
      dst_bank        VARCHAR2(2),
      amount          NUMBER(19,4) NOT NULL,
      idempotency_key VARCHAR2(100) NOT NULL,
      created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT ux_txn_idemp UNIQUE (idempotency_key)
    )
  ';

  EXECUTE IMMEDIATE '
    CREATE TABLE holds (
      hold_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
      account_id      NUMBER(19) NOT NULL,
      amount          NUMBER(19,4) NOT NULL,
      status          VARCHAR2(1) DEFAULT ''O'' NOT NULL,
      idempotency_key VARCHAR2(100) NOT NULL,
      created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_hold_account FOREIGN KEY (account_id) REFERENCES accounts(account_id),
      CONSTRAINT ux_hold_idemp UNIQUE (idempotency_key)
    )
  ';

  EXECUTE IMMEDIATE '
    CREATE TABLE ledger_entries (
      entry_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
      txn_id      NUMBER(19) NOT NULL,
      account_id  NUMBER(19) NOT NULL,
      amount      NUMBER(19,4) NOT NULL,
      created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_ledger_txn     FOREIGN KEY (txn_id)    REFERENCES transactions(txn_id),
      CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts(account_id)
    )
  ';

  -- 2. 계정 잔액 초기화
  EXECUTE IMMEDIATE 'UPDATE accounts SET balance = 0, hold_amount = 0';

  -- 3. 특정 계정에 초기 잔액 설정 (테스트용)
  EXECUTE IMMEDIATE '
    UPDATE accounts
    SET balance = 100000000
    WHERE account_id IN (300001, 300002, 300003, 300004, 300005)
  ';

  COMMIT;
END;
