-- Oracle 데이터 초기화 및 IDENTITY 시퀀스 리셋

-- 1. 트랜잭션 데이터 삭제 (순서 중요: 자식 → 부모)
DELETE FROM ledger_entries;
DELETE FROM holds;
DELETE FROM transactions;

-- 2. 계정 잔액 초기화
UPDATE accounts
SET balance = 0, hold_amount = 0;

-- 3. 특정 계정에 초기 잔액 설정 (테스트용)
UPDATE accounts
SET balance = 100000000
WHERE account_id IN (300001, 300002, 300003, 300004, 300005);

COMMIT;

-- 4. IDENTITY 시퀀스 리셋 (Oracle 12c+)
-- RESTART 키워드 대신 DROP & RECREATE
ALTER TABLE transactions MODIFY txn_id DROP IDENTITY;
ALTER TABLE transactions MODIFY txn_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

ALTER TABLE holds MODIFY hold_id DROP IDENTITY;
ALTER TABLE holds MODIFY hold_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

ALTER TABLE ledger_entries MODIFY entry_id DROP IDENTITY;
ALTER TABLE ledger_entries MODIFY entry_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- 확인 쿼리 (옵션)
-- SELECT 'transactions' as table_name, COUNT(*) as row_count FROM transactions
-- UNION ALL
-- SELECT 'holds', COUNT(*) FROM holds
-- UNION ALL
-- SELECT 'ledger_entries', COUNT(*) FROM ledger_entries
-- UNION ALL
-- SELECT 'accounts with balance', COUNT(*) FROM accounts WHERE balance > 0;
