-- Oracle 데이터 초기화 및 IDENTITY 시퀀스 리셋 (TRUNCATE 버전 - 로그 없음, 빠름)
-- 주의: TRUNCATE는 롤백 불가능, DDL 문이므로 암묵적 COMMIT 발생

-- 1. 트랜잭션 데이터 삭제 (TRUNCATE는 훨씬 빠름, 로그 미생성)
TRUNCATE TABLE ledger_entries;
TRUNCATE TABLE holds;
TRUNCATE TABLE transactions;

-- 2. 계정 잔액 초기화
UPDATE accounts
SET balance = 0, hold_amount = 0;

-- 3. 특정 계정에 초기 잔액 설정 (테스트용)
UPDATE accounts
SET balance = 100000000
WHERE account_id IN (300001, 300002, 300003, 300004, 300005);

COMMIT;

-- 4. IDENTITY 시퀀스 리셋 (Oracle 12c+)
-- TRUNCATE 후에도 시퀀스는 리셋되지 않으므로 별도 실행 필요
ALTER TABLE transactions MODIFY txn_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART);
ALTER TABLE holds MODIFY hold_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART);
ALTER TABLE ledger_entries MODIFY entry_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART);

-- 확인 쿼리 (옵션)
-- SELECT 'transactions' as table_name, COUNT(*) as row_count FROM transactions
-- UNION ALL
-- SELECT 'holds', COUNT(*) FROM holds
-- UNION ALL
-- SELECT 'ledger_entries', COUNT(*) FROM ledger_entries
-- UNION ALL
-- SELECT 'accounts with balance', COUNT(*) FROM accounts WHERE balance > 0;
